version: "3.5"
services:
  mrtg:
    build: .
    hostname: mrtg
    restart: always
    ports:
      - "8880:80"
    volumes:
      - "./conf.d:/etc/mrtg/conf.d"
      - "./html:/mrtg/html"
    environment:
        TZ: "Australia/Victoria"
        HOSTS: 'public:202.144.175.136'
        USERID: 100
        GROUPID: 101
        REGENERATEHTML: "yes"
        INDEXMAKEROPTIONS: ""
    tmpfs:
      - "/run"
